# -	start with a base image.
FROM node:16-alpine

# -	setting up a working directory
WORKDIR '/app'

# -	Copy over package.json to the current working directory of /app
COPY package.json .

# RUN npm install to install all our dependencies
RUN npm install
RUN npm install -g npm@8.4.1

# -	Copy over everything else from the project directory.
COPY . .

# -	Run the command to start up the project
CMD ["npm", "run", "start"]